### ISSUE TITLE
Validator - View should adjust when filtering out info, warnings, or errors.

### ISSUE THREAD

**Issue by DJmerkury** [cpr2323/A8Manager#53] opened 2023-08-02 21:00 UTC
Currently the screen just appears blank when removing a lot of entries and you have to manually scroll up.

**Comment by cpr2323** [comment] 2023-08-02 21:45
Closing as duplicate of: https://github.com/cpr2323/A8Manager/issues/46

**Closed by cpr2323** 2023-08-02 21:45 UTC
